### ISSUE TITLE
No line breaks, lack of indent in list

### ISSUE THREAD

**Issue by Alvarofg** [svivian/q2a-markdown-editor#11]
Hi, I'm having issues with the markdown editor, as it doesn't seem to allow having a blank line break, as in here...

(blank)
Also, lists are not getting indented

An example is here:
http://respuestas.ca/544/que-se-puede-traer-de-usa-sin-pagar-duty-ni-impuestos 

Thanks

**Comment by svivian** [comment]
The problem is you have overridden the default margins for paragraphs and lists. You need to add something like this to your stylesheet:

    p {
        margin: 1em 0;
    }
    ul, ol {
        margin-left: 2em;
    }

**Comment by Alvarofg** [comment]
Thanks, Indeed, it looks like I might have a conflict with embed videos plugging ( https://github.com/NoahY/q2a-embed/blob/master/thickbox.css ). I have to check more

/* ----------------------------------------------------------------------------------------------------------------*/
/* ---------->>> global settings needed for thickbox <<<-----------------------------------------------------------*/
/* ----------------------------------------------------------------------------------------------------------------*/
*{padding: 0; margin: 0;}

Thanks for answering
