### ISSUE TITLE
Markup editor won't show up Q2A 1.7

### ISSUE THREAD

**Issue by vuk** [svivian/q2a-markdown-editor#13]
Is this plugin compatible with 1.7? I can't make it work. Won't show up as an option

**Comment by svivian** [comment]
Yes it should be working fine. It works on my site with 1.7.

Are you getting any errors in your logs? Or any Javascript errors in the console? (Press Ctrl+Shift+I in your browser to open dev tools.)

**Comment by vuk** [comment]
I've fixed it. My mistake. Sorry about it
