### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by M42** [svivian/q2a-markdown-editor#18]
I have installed the plugin in the `qa-plugin/` folder and I have activated it on the admin panel. Markdown renders perfectly, but the preview is not showing. Am I missing something?

**Comment by M42** [comment]
I was, it was a permissions issue, as in #13.

Maybe it would be a good idea to add a note to the installation instructions asking to check that the folder has the correct permissions. It is obvious, but a common mistake.

**Comment by svivian** [comment]
What was the specific problem? Which file(s) needed different permissions?

**Comment by M42** [comment]
When I downloaded the zip, I found all the files on the repository with the same following permissions: (`-rw-rw-r--`)
``` bash
$ ls -l
-rw-rw-r-- 1 root root 43831 jul 31  2015 inc.markdown.php
-rw-rw-r-- 1 root root   429 jul 31  2015 metadata.json
drw-rw-r-- 2 root root  4096 feb 19 13:39 pagedown
-rw-rw-r-- 1 root root  3628 jul 31  2015 qa-markdown-editor.php
-rw-rw-r-- 1 root root   906 jul 31  2015 qa-markdown-viewer.php
-rw-rw-r-- 1 root root   713 jul 31  2015 qa-md-events.php
-rw-rw-r-- 1 root root   559 jul 31  2015 qa-md-lang-default.php
-rw-rw-r-- 1 root root  1356 jul 31  2015 qa-md-layer.php
-rw-rw-r-- 1 root root  1572 jul 31  2015 qa-plugin.php
-rw-rw-r-- 1 root root  3060 jul 31  2015 README.md
```
But the plugin only started to appear in the administration center (I think) when I gave all of them execution permission: (`-rwxrwxr-x`)
``` bash
$ chmod 775 . -R
$ ls -l
-rwxrwxr-x 1 root root 43831 jul 31  2015 inc.markdown.php
-rwxrwxr-x 1 root root   429 jul 31  2015 metadata.json
drwxrwxr-x 2 root root  4096 feb 19 13:39 pagedown
-rwxrwxr-x 1 root root  3628 jul 31  2015 qa-markdown-editor.php
-rwxrwxr-x 1 root root   906 jul 31  2015 qa-markdown-viewer.php
-rwxrwxr-x 1 root root   713 jul 31  2015 qa-md-events.php
-rwxrwxr-x 1 root root   559 jul 31  2015 qa-md-lang-default.php
-rwxrwxr-x 1 root root  1356 jul 31  2015 qa-md-layer.php
-rwxrwxr-x 1 root root  1572 jul 31  2015 qa-plugin.php
-rwxrwxr-x 1 root root  3060 jul 31  2015 README.md
```

**Comment by svivian** [comment]
You shouldn't need execute permissions on PHP files. Your first set of permissions is exactly what I have on the plugin on my site and it works fine. And if everything is working besides the preview, then the permissions are correct for most of the files. Perhaps one of the `Markdown.*.js` files had incorrect permissions?

**Comment by M42** [comment]
At first I thought that it was the preview the only problem, but in fact Markdown is not rendered if the plugin folder does not have the correct permissions. I can make it start or end working by executing `chmod 775 .` or `chmod 774 .` on the plugin folder.
I imagine it is a problem with the execution persmission last bit (`-rwxrwxrw?`) of the main folder and it does affect all the plugin, not only preview as I was thinking previously.

**Comment by lalitofficial** [comment]
@svivian In my case the permissions to Markdown.*.js + the png files was 0644 .. i did 755 and believe me it worked
