### ISSUE TITLE
How to make wmd-button-bar image scrollable?

### ISSUE THREAD

**Issue by fardina** [svivian/q2a-markdown-editor#27]
Hi Scott
Thank you for the plugin.
In the small devices the button bar is invisible. How to make it scrollable like this site(pokemondb):
![pokemondb](https://user-images.githubusercontent.com/13521621/59414788-7744e680-8dd7-11e9-87cf-0583c1ac3ca0.png)

At the moment it's not visible in snowflat theme:
![q2a](https://user-images.githubusercontent.com/13521621/59414849-9a6f9600-8dd7-11e9-9764-277f526e65dd.png)

Thanks.

**Comment by svivian** [comment]
Hi, sorry for the late reply. On my site I use the CSS property `overflow-x: auto` which adds the scrollbar in the x (horizontal direction.

```
.wmd-button-bar {
    width: 100%;
    padding: 5px 0;
    overflow-x: auto;
    overflow-y: hidden;
}
```

**Comment by fardina** [comment]
Thank you for your answer. But that doesn't work correctly for me. It's not possible to scroll to the hidden icons. I use Snowflat Theme.
![mdeditr](https://user-images.githubusercontent.com/13521621/61971943-8f726d00-aff5-11e9-9a68-bb7ce41db7bd.png)
